notARepository: 'skip'
promptToReturnFromSubprocess: false
gui:
  nerdFontsVersion: "3"
  switchTabsWithPanelJumpKeys: true
  showNumstatInFilesView: true
  spinner:
    rate: 5000
keybinding:
  files:
    viewResetOptions: 'G'
  commits:
    viewResetOptions: 'G'
git:
  fetchAll: false
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
customCommands:
  - key: 'p'
    context: 'global'
    description: 'Pull current branch only'
    command: 'git pull {{.CheckedOutBranch.UpstreamRemote}} {{.CheckedOutBranch.UpstreamBranch}}'
    loadingText: 'Pulling current branch...'
